name: Publish to npm

# main ブランチに push されたら実行する例
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 1) リポジトリをチェックアウト
      - name: Check out the repo
        uses: actions/checkout@v3

      # 2) Node.jsをセットアップ (バージョンは適宜変更)
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      # 3) 依存関係のインストール & ビルド
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 4) npm publish
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
